namespace Model.Enums;

public enum EAddonType
{
    MACHINE_GUN,
    VULCAN_GUN,
    SMALL_STORAGE,
    NUCLEAR_REACTOR,
    HEAVY_GUN,
    ARMOR,
    LARGE_STORAGE,
    GREENHOUSE,
    HEAVY_ARMOR,
    BIO_FUEL_GENERATOR,
    HEAVY_LARGE_STORAGE,
    GAUSSA_GUN,
    SMALL_NUCLEAR_REACTOR,
    MAINTENANCE_DRONE,
    ZURAW,
    TURBO_BAGPIPER
}